### ISSUE TITLE
issue with task 4 while running TIRSPECdataReduction.py in mac os x el capitan

### ISSUE THREAD

**Issue by namithaissac** [indiajoe/TIRSPEC#14]
This error pops up every time i try running the TIRSPECdataReduction.py script on my mac OS X el capitan version. but it seems to work fine on linux.

Steps you have already finished : 1 2 3 
Enter the list : 4
Time now: Mon Jul 25 10:06:13 2016
RUNNING TASK:4  Combine images in a Dither [,subtract sky], apply Flat Correction and Bad pixel interpolation

Output directory /Users/namithaissac/Documents/EGOG12.42+0.50/G12.42+0.50/NAMITHA/20140926 already exists.
 Everything inside it will be overwritten.
Working on night: 20140926
TIRSPECdataReduction.py:1128: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  statlist.append(statfunction(pyfits.getdata(img)[Ymin-1:Ymax,Xmin-1:Xmax]))
median of images: [-0.066154473, -0.22823668, -0.22276227, -0.20556127, -0.22107205, -0.21710287, -0.17962617]
Zeroshifts of images: [-0.12534779  0.03673442  0.03126001  0.01405901  0.02956979  0.02560061
 -0.01187609] :: ImgAvg =-0.191502258182

Jul 25 10:06: IMCOMBINE
  combine = median, scale = none, zero = @/Users/namithaissac/Documents/EGOG12.42+0.50/G12.42+0.50/NAMITHA/20140926/G1242-24_median_G1242-30.fits_zeroshifts.txt, weight = none
  reject = sigclip, mclip = yes, nkeep = 1
  lsigma = 3., hsigma = 3.
  blank = 0.
  statsec = Jul 25 10:06
                Images     Zero
  20140926/Slope-G1242-24.fits -0.1253
  20140926/Slope-G1242-25.fits 0.03673
  20140926/Slope-G1242-26.fits 0.03126
  20140926/Slope-G1242-27.fits 0.01406
  20140926/Slope-G1242-28.fits 0.02957
  20140926/Slope-G1242-29.fits  0.0256
  20140926/Slope-G1242-30.fits -0.0119

  Output image = /Users/namithaissac/Documents/EGOG12.42+0.50/G12.42+0.50/NAMITHA/20140926/G1242-24_median_G1242-30.fits, ncombine = 7
Image section used for normalising Flat is [200:800,200:800]

Jul 25 10:06: IMCOMBINE
  combine = median, scale = median, zero = none, weight = none
  reject = sigclip, mclip = yes, nkeep = 1
  lsigma = 3., hsigma = 3.
  blank = 0.
  statsec = Jul 25 10:06
                Images   Median  Scale
  20140926/Slope-Continuum-40.fits  503.63  1.000
  20140926/Slope-Continuum-39.fits  502.54  1.002
  20140926/Slope-Continuum-41.fits  505.03  0.997

  Output image = /Users/namithaissac/Documents/EGOG12.42+0.50/G12.42+0.50/NAMITHA/20140926/G1242-24_median_G1242-30_flat.fits, ncombine = 3
Traceback (most recent call last):
  File "TIRSPECdataReduction.py", line 1928, in <module>
    main()
  File "TIRSPECdataReduction.py", line 1885, in main
    CombDith_FlatCorr_subrout(PC,method=PC.IMGCOMBMETHOD)
  File "TIRSPECdataReduction.py", line 1230, in CombDith_FlatCorr_subrout
    if (PC.TODO == 'S') and (PC.CONTINUUMGRADREMOVE == 'Y'):
AttributeError: 'PipelineConfig' object has no attribute 'CONTINUUMGRADREMOVE'

**Comment by indiajoe** [comment]
Thanks for reporting the issue.
Could you confirm you are using the latest version of the code?
The one downloaded from this link is the latest.
https://github.com/indiajoe/TIRSPEC/tarball/master

Or you can also check whether, towards the end of the .conf file do you have the term
`REMOVE_CONTINUUM_GRAD=`

**Comment by namithaissac** [comment]
I was using the older version of the code. The has been been rectified now.
thank you

**Comment by indiajoe** [comment]
Okay, Thanks. I shall close this issue then. :)
